<?php

namespace Database\Factories;

use App\Models\Menu_Item;
use App\Models\Restaurant;
use Faker\Generator as Faker;
use Illuminate\Database\Eloquent\Factories\Factory;

class Menu_ItemFactory extends Factory
{
    protected $model = Menu_Item::class;

    // Define an array of item names
    protected $itemNames = [
        "Spaghetti Carbonara",
        "Chicken Alfredo",
        "Grilled Salmon",
        "Caesar Salad",
        "Margherita Pizza",
        "Pad Thai",
        "Roast Chicken",
        "Fish and Chips",
        "Beef Bourguignon",
        "Steak Frites",
        "Tuna Poke Bowl",
        "Falafel Wrap",
        "Tomato Soup",
        "Lasagna",
        "Burger and Fries",
        "Sushi Roll",
        "Shrimp Scampi",
        "Miso Soup",
        "Chicken Teriyaki",
        "Beef Stroganoff",
        "Beef Brisket",
        "Lamb Chops",
        "Roast Beef",
        "Eggplant Parmesan",
        "Chicken Tikka Masala",
        "Butter Chicken",
        "Chana Masala",
        "Tandoori Chicken",
        "Naan Bread",
        "Chicken Shawarma",
        "Hummus and Pita",
        "Gyro",
        "Tabbouleh Salad",
        "Lentil Soup",
        "Falafel Plate",
        "Shakshuka",
        "Roasted Vegetables",
        "Veggie Burger",
        "Cobb Salad",
        "Spinach and Feta Omelette",
        "Pancakes and Bacon",
        "French Toast",
        "Eggs Benedict",
        "Biscuits and Gravy",
        "Huevos Rancheros",
        "Pho",
        "Banh Mi",
        "Bun Cha",
        "Spring Rolls",
        "Beef Noodle Soup",
        "Fried Rice",
        "Chow Mein",
        "Kung Pao Chicken",
        "General Tso's Chicken",
        "Dim Sum",
        "Hot and Sour Soup",
        "Mongolian Beef",
        "Peking Duck",
        "Mapo Tofu",
        "Ramen",
        "Tonkatsu",
        "Udon Noodle Soup",
        "Soba Noodles",
        "Takoyaki",
        "Okonomiyaki",
        "Sukiyaki",
        "Sashimi",
        "Tempura",
        "Yakitori",
        "Matcha Ice Cream",
        "Mochi",
        "Red Bean Paste Buns",
        "Dumplings",
        "Baozi",
        "Kimchi",
        "Bulgogi",
        "Japchae",
        "Galbi",
        "Bibimbap",
        "Kimbap",
        "Tteokbokki",
        "Samgyeopsal",
        "Sundubu Jjigae",
        "Haemul Pajeon",
        "Naengmyeon",
        "Bingsu",
        "Tiramisu",
        "Cheesecake",
        "Creme Brulee",
        "Chocolate Mousse",
        "Panna Cotta",
        "Key Lime Pie",
        "Apple Pie",
        "Blueberry Muffin",
        "Cinnamon Roll",
        "Banana Bread",
        "Croissant",
        "Bagel and Cream Cheese",
        "English Muffin",
        "Scone",
        "Quiche",
        "Caprese Salad",
        "Greek Salad",
        "Niçoise Salad",
        "Caesar Salad",
        "Cobb Salad",
        "Wedge Salad",
        "Fruit Salad",
        "Panzanella Salad",
        "Tabbouleh Salad",
        "Fattoush Salad"
    ];

    public function definition()
    {
        return [
            'restaurant_id' => function () {
                return Restaurant::all()->random()->id;
            },
            // Select a random item name from the array
            'item_name' => $this->faker->randomElement($this->itemNames),
            'item_description' => $this->faker->paragraph(),
            'item_price' => $this->faker->randomFloat(2, 5, 50),
        ];
    }
}
